name = "lf"
package_name = "lf"
url_template = "https://github.com/gokcehan/lf"
description = "lf (as in list files) is a terminal file manager written in Go with a heavy inspiration from ranger file manager. "
terminal = true
formats = ["tarball"]

[metadata]
maintainer = "gokcehan"
license = "MIT"
