name = "Waterfox"
package_name = "waterfox"
url_template = "https://cdn.waterfox.com/waterfox/releases/$wf_ver/Linux_x86_64/waterfox-$wf_ver.tar.bz2"
description = "A privacy-focused web browser based on Firefox, optimized for performance and customization."
terminal = false
formats = ["tarball"]
icon_url = "https://www.waterfox.com/_astro/app-icon-dark.CwYTjDIq.png"
screenshots = [
  "https://www.waterfox.com/_astro/dark-tst.DZiOIaKf_Z2mFk5k.png"
]

[metadata]
maintainer = "Waterfox-Project"
license = "MPL-2.0 license"
